### ISSUE TITLE
Add tests for haddp

### ISSUE THREAD

**Issue by wolfv** [QuantStack/xsimd#119]
Currently haddp is untested (and unused).

**Comment by jpetkau** [comment]
haddp is also broken on most (all?) platforms: it takes `const simd_batch<batch_type>* row` and indexes `row[0]`, `row[1]` etc., but `sizeof(simd_batch<T>)==1` because it's an empty base class, so this ends up offsetting by bytes instead of batches.

**Comment by JohanMabille** [comment]
Fixed in #282
