### ISSUE TITLE
Can not build with Intel Compiler on MSVC because cmake fails

### ISSUE THREAD

**Issue by emmenlau** [QuantStack/xsimd#125]
Currently the build fails for me with the latest Intel Compiler on MSVC (and Visual Studio 2015). The build aborts in cmake configuration with error
```
-- Performing Test HAS_CPP11_FLAG
-- Performing Test HAS_CPP11_FLAG - Failed
CMake Error at test/CMakeLists.txt:53 (message):
  Unsupported compiler -- xsimd requires C++11 support!

-- Configuring incomplete, errors occurred!
```
I assume the detection is not perfect, because the Intel Compiler has support for `C++11`. Is there anything I can do to help?

**Comment by SylvainCorlay** [comment]
Hey @emmenlau, thanks for reporting. I don't think that any of us has experience with the intel compiler, but from your report, it seems that it would require us to special case  for that compiler in the  CMakeLists https://github.com/QuantStack/xsimd/blob/master/test/CMakeLists.txt#L37

**Comment by emmenlau** [comment]
Dear Sylvain, I agree that this looks suspicious. Actually looking at the code, I think that the `if ... OR CMAKE_CXX_COMPILER_ID MATCHES "Intel"` is written specifically for the Intel Compiler on Unix/Linux. AFAIK on MSVC there is no need for specific options to enable `C++11`, neither for MSVC nor for the Intel Compiler. But since I'm no expert on Windows builds, please take my words with a grain of salt.

**Comment by JohanMabille** [comment]
@emmenlau indeed no flag is required on windows to get C++11 / C++14 support enabled

**Comment by JohanMabille** [comment]
The issue was closed due to the merge of #127, however since I'm not sure that everything is fine in the cmake for Intel on Windows, I reopen it until @emmenlau confirms everything is fine.

**Comment by emmenlau** [comment]
Dear @JohanMabille , is it fine if I wait for the next release before testing it? Its slightly easier with my cross-platform build system. Is the next release to be expected soon?

**Comment by JohanMabille** [comment]
No problem, the next release should be out next week when the support for complex has been integrated.

**Comment by JohanMabille** [comment]
@emmenlau We just release xsimd 6.0.0, let us know if the compilation on Windows with Intel is fine now.

**Comment by emmenlau** [comment]
Great, yes its fixed now. I still get a similar error for xtensor but I will report it there.
