### ISSUE TITLE
std::nextafter

### ISSUE THREAD

**Issue by serge-sans-paille** [QuantStack/xsimd#158]
For API completness, it would be great to have support for [nextafter](https://en.cppreference.com/w/cpp/numeric/math/nextafter)

**Comment by serge-sans-paille** [comment]
Boost.simd reference implementation: https://github.com/JohanMabille/boost.simd/blob/develop/include/boost/simd/arch/common/simd/function/nextafter.hpp

**Comment by wolfv** [comment]
There seems also to be a implementation in Sleef: https://github.com/shibatch/sleef/blob/86d5c2d6d87b6ecdaff88ec2e1130d62dac6c885/src/libm/sleefdp.c#L2200
