### ISSUE TITLE
batch<uint32_t, ...> and batch <uint64_t, ...>

### ISSUE THREAD

**Issue by serge-sans-paille** [QuantStack/xsimd#161]
There is support for a batch of ``int32_t``, but nothing for ``uint32_t``. Same applies to ``uint64_t``.

**Comment by serge-sans-paille** [comment]
Same holds for ``batch<int16_t,...>`` and probably others.

**Comment by wolfv** [comment]
The missing ones are 

int16, uint16, uint32, uint64

However, we should be able to move quickly on those (at least for intel) because we have these new int base classes:

https://github.com/QuantStack/xsimd/blob/master/include/xsimd/types/xsimd_avx_int8.hpp#L136

**Comment by JohanMabille** [comment]
This has been impleented in #171
