### ISSUE TITLE
Missing int types for NEON and AVX512

### ISSUE THREAD

**Issue by wolfv** [QuantStack/xsimd#176]
We still need to implement the `int16, uint16, uint32, uint64` for AVX512 and ARM NEON.

**Comment by martinRenou** [comment]
- [x]  int16 AVX512
- [x]  uint16 AVX512
- [x]  uint32 AVX512
- [x]  uint64 AVX512
- [ ]  int16 NEON
- [ ]  uint16 NEON
- [ ]  uint32 NEON
- [ ]  uint64 NEON

**Comment by martinRenou** [comment]
Done!

**Comment by wolfv** [comment]
**NICE**
