### ISSUE TITLE
Macro definition __LITTLE_ENDIAN breaks the build

### ISSUE THREAD

**Issue by jpcima** [QuantStack/xsimd#178]
The source file `xsimd_rem_pio2.hpp` defines the macro `__LITTLE_ENDIAN` under some conditions.

If such a condition is met on Linux systems, as I was told it could happen under Debian package building environment, the macro can redefine the system's definition in `endian.h`.

This can result in a failure in a following conditional such as this:
`#       if defined(__LITTLE_ENDIAN) && (__BYTE_ORDER == __LITTLE_ENDIAN)`

In case of using the Gcc or Clang compiler, maybe xsimd can use the builtin macros of these compilers instead?

**Comment by JohanMabille** [comment]
Fixed in #179
