### ISSUE TITLE
Missing xsimd implementation for some complex operations

### ISSUE THREAD

**Issue by serge-sans-paille** [QuantStack/xsimd#184]
According to the Pythran test suite, the following math noperators miss their xsimd version for complex vector arguments:

- conj
- floor
- exp
- expm1
- log
- log1p
- log2
- conj
- arctan
- sign

Given that numpy gives them a semantic, it also applies to:

- fmax
- fmin
- max
- min

On the positive note, all arithmetic operators seem to work just fine!

**Comment by JohanMabille** [comment]
The following operations are already implemented (and tested) in `xsimd/math/xsimd_math_complex.hpp` : 

- conj
- floor
- exp
- log
- log2
- atan

The following are missing:

- expm1
- log1p
- log2
- sign

`xsimd/math/xsimd_math_complex.hpp` is included in `xsimd.hpp` only, but I guess you are using lower level APIs of xsimd, so this might be a missing include?

**Comment by serge-sans-paille** [comment]
I'm not using lower APIs :-/ The missing symbol is ``undefined symbol: _ZN5xsimd5floorISt7complexIdELm4EEENS_5batchIT_XT0_EEERKS5_``, if that can help.
