### ISSUE TITLE
Dropping C++11 support in favor of C++14 support

### ISSUE THREAD

**Issue by JohanMabille** [QuantStack/xsimd#248]
We are introducing more and more workarounds in the library to keep support of C++11; besides, `xsimd` depends on parts of the [xtl](https://github.com/QuantStack/xtl) that are C++11-compatible, and this limits the refactoring possibilities of these parts.

I would like the next major release of `xsimd` to be full C++14, is there any blocker in `xsimd` client libraries?

**Comment by serge-sans-paille** [comment]
it would be a limitation for pythran, as pythran only requires c++11 from the abckend compiler.
The reason why we require that is that we only require gcc5 or clang3.5 as build dependency.

**Comment by JohanMabille** [comment]
Not sure to get it, from what I know gcc5 and clang 3.5 have full suppor tof C++14.

**Comment by JohanMabille** [comment]
Several dependencies of  xsimd are C++11, so let's keep it!

**Comment by serge-sans-paille** [comment]
Thanks o/

**Comment by JohanMabille** [comment]
I should have closed that sooner, I'll update the README accordingly.
