### ISSUE TITLE
Compilation error first example in README 

### ISSUE THREAD

**Issue by paugier** [QuantStack/xsimd#284]
Trying to compile the first example in the README.md (https://github.com/QuantStack/xsimd#explicit-use-of-an-instruction-set-extension), I get:

```
g++ main.cpp  -I $HOME/miniconda3/include
main.cpp: In function ‘int main(int, char**)’:
main.cpp:9:27: error: variable ‘xsimd::batch<double, 4> a’ has initializer but incomplete type
     xs::batch<double, 4> a(1.5, 2.5, 3.5, 4.5);
                           ^
main.cpp:10:27: error: variable ‘xsimd::batch<double, 4> b’ has initializer but incomplete type
     xs::batch<double, 4> b(2.5, 3.5, 4.5, 5.5);
```

xsimd installed with conda... I guess I'm doing something wrong but what?

**Comment by JohanMabille** [comment]
Can you check you have AVX instruction set on your system? Also did you build with `-march=native`  flag?

**Comment by paugier** [comment]
> Can you check you have AVX instruction set on your system?

Yes this behavior is obtained on computers with AVX.

> Also did you build with -march=native flag?

No error with `g++ -march=native main.cpp -I $HOME/miniconda3/include`.

**Comment by JohanMabille** [comment]
NIce! I'll update the README so people don't get this error anymore. Thanks for reporting!

**Comment by JohanMabille** [comment]
The README has been updated, this can be colsed.
