### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by skeletonyk** [QuantStack/xsimd#300]
I got this compiling error when trying to compile with c++17 standard.  it seems to have problem with the redefinition of ` size_t get_alignment_offset` and `inline size_t get_alignment_offset`? Am I doing anything wrong? Thanks.

`
/home/kyu/lib/xsimd-7.2.5/prefix/include/xsimd/memory/xsimd_aligned_allocator.hpp:313:19: error: redefinition of ‘template<class T> size_t xsimd::get_alignment_offset(const T*, size_t, size_t)’
inline size_t get_alignment_offset(const T* p, size_t size, size_t block_size)
`

**Comment by wolfv** [comment]
How did you fix it?
