### ISSUE TITLE
CMakeLists.txt compliant with Debian packaging

### ISSUE THREAD

**Issue by JohanMabille** [QuantStack/xsimd#32]
Following changes are required:

- [x] download gtest instead of using local installation
- [x] test installed package instead of local one
- [x] remove CMAKE_SIZEOF_VOID_P from xsimdConfigVersion.cmake

**Comment by ghisvail** [comment]
So I am guessing version 3.0 will be the one I should consider packaging in the future, right?

**Comment by JohanMabille** [comment]
Yes.
