### ISSUE TITLE
batch<float, 8>::store_unaligned() segfaults

### ISSUE THREAD

**Issue by ukoethe** [QuantStack/xsimd#92]
In `xsimd_avx_float.hpp`, the function `batch<float, 8>::store_unaligned()` calls the aligned intrinsic `_mm256_store_ps()` instead of the unaligned `_mm256_storeu_ps()`, leading to a segfault when the address is actually unaligned. I didn't check if the same problem occurs for other types.

**Comment by JohanMabille** [comment]
Thanks for the report! That should work now (I fixed it in other batches too).

**Comment by ukoethe** [comment]
Yes, works. Thanks!
